<?php

// LO SPECIFICATION PATTERN CONSENTE NEL CREARE DEGLI OGGETTI DI "SPECIFICA",
// QUESTI OGGETTI RICEVONO UN ISTANZA DI ALTRO OGGETTO E APPLICANO LA SPECIFICA SULL'OGGETTO PASSATO
// CustomerIsGold è UNA CLASSE DI SPECIFICA CHE APPLICA UNA SORTA DI FILTRO SULL'OGGETTO RICEVUTO (CUSTOMER)
// QUESTO PATTERN SERVE PER ESTERNARE LA LOGICA DI FILTRO FUORI DALLA CLASSE A CUI VIENE APPLICATA.
// (UN UTLIZZO COMUNE LO SI TROVA NEI TEST O NEI REPOSITORY PER FILTRARE LA QUERY)
// QUI UN ESEMPIO PRATICO DI QUERY BASATO SULLE PROPRIETà DELL'OGGETTO isSatisfiedBy() E SU QUERY asScope()
// SUL METODO isSatisfiedBy() VIENE PASSATA UN ISTANZA DI CUSTOMER E VIENE VERIFICATO SE è DI TIPO GOLD
// SUL METODO asScope() VIENE PASSATA UNA QUERY BASATA SULL'OGGETTO CUSTOMER E VIENE FILTRATA
// CON QUESTO SISTEMA PORTIAMO LOGICA DI FILTRO FUORI DALL'OGGETTO SU CUI VIENE APPLICATA.


class CustomerIsGold
{
    public function isSatisfiedBy(Customer $customer)
    {
        return $customer->type() == 'gold';
    }

    public function asScope($query)
    {
        return $query->where('type', 'gold');
    }
}